### ISSUE TITLE
fetch-swagger-schema:

### ISSUE THREAD

**Issue by OwenBrotherwood** [signalfx/swagger-client-generator#10]
It seems that fetch-swagger-schema: does not support v2 
Does swagger-client-generator support v2?

fetch-swagger-schema:
fetch-swagger-schema http://petstore.swagger.io/v2/swagger.json
[TypeError: Cannot read property 'length' of undefined]

**Comment by unsetbit** [comment]
Unfortunately, our libraries currently only support v1.2, we're slowly moving towards v2, but I can't provide a timeline yet.
