### ISSUE TITLE
npm install fail for petstore

### ISSUE THREAD

**Issue by balamanian** [signalfx/swagger-client-generator#7]
C:\Users\bponmari\Downloads\swagger\swagger-client-generator-master\swagger-client-generator-master>npm install petstore.swagger.wordnik.com -g fetch-swagger-schema; fetch-swagger-schema  http://petstore.swagger.wordnik.com/api/api-docs petstore
npm ERR! not a package C:\Users\bponmari\AppData\Local\Temp\npm-20136-ZbxOxcCe\petstore.swagger.wordnik.com\api\api-docs
npm ERR! Error: ENOENT, open 'C:\Users\bponmari\AppData\Local\Temp\npm-20136-ZbxOxcCe\petstore.swagger.wordnik.com\api\api-docs-unpack\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "petstore.swagger.wordnik.com" "-g" "fetch-swagger-schema;" "fetch-swagger-schema" "http://petstore.swagger.wordnik.com/api/api-docs" "petstore"
npm ERR! cwd C:\Users\bponmari\Downloads\swagger\swagger-client-generator-master\swagger-client-generator-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\bponmari\AppData\Local\Temp\npm-20136-ZbxOxcCe\petstore.swagger.wordnik.com\api\api-docs-unpack\package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\bponmari\Downloads\swagger\swagger-client-generator-master\swagger-client-generator-master\npm-debug.log
npm ERR! not ok code 0

C:\Users\bponmari\Downloads\swagger\swagger-client-generator-master\swagger-client-generator-master>

**Comment by oztu** [comment]
Your command is malformed: `npm install petstore.swagger.wordnik.com -g fetch-swagger-schema; fetch-swagger-schema http://petstore.swagger.wordnik.com/api/api-docs petstore` Instructs npm to install petstore.swagger.wordnik.com (which isn't a package). I think the command you're looking for is `npm install -g fetch-swagger-schema; fetch-swagger-schema http://petstore.swagger.wordnik.com/api/api-docs ./petstore.json` . 

Unfortunately, the petstore example provided by the Swagger team has moved onto Swagger 2.0, which isn't supported by this library yet (this library was written to the Swagger 1.2 spec). As such, the petstore example no longer works.
