### ISSUE TITLE
How resolve got error message generate java client

### ISSUE THREAD

**Issue by balamanian** [signalfx/swagger-client-generator#8]
Hi, when i try to generate the java clien using swagger client gen. i was getting below error, please give me hint to solve this. Please explain to me, what those error mean to.

********* Failed to read swagger json!
Error: Operation - httpMethod | missing required field
Error: Operation - responseClass | missing required field
Warning: Operation Parameter - description | missing recommended field
Error: Operation Parameter - dataType | missing required field
Error: Operation - httpMethod | missing required field

**Comment by oztu** [comment]
It looks like your generated swagger schema is missing fields which are required. Are you able to post your original schema?
